sudo: required
jobs:
  include:
    - stage:
      language: python
      services:
        docker
      env:
        - TOXENV=flake8
      before_install: docker build -t axe-selenium-python .
      install: skip
      script:
        - docker run -e TOXENV=$TOXENV axe-selenium-python tox
    - stage:
      language: python
      services:
        docker
      env:
        - TOXENV=py36
      before_install: docker build -t axe-selenium-python .
      install: skip
      script:
        - docker run -e TOXENV=$TOXENV axe-selenium-python tox
